### ISSUE TITLE
Populate project with remote repositories that can be added to virtual repositories

### ISSUE THREAD

**Issue by cpf-bc** [bcgov/platform-services-archeobot#15]
For Java builds we want to use a single virtual repository URL that we can supply to maven to resolve all dependencies.
Currently users cannot create and consequently add remote repositories to the virtual repository, as shown in screenshot below (only local repositories can be added):

<img width="868" alt="Screen Shot 2022-06-03 at 1 16 59 PM" src="https://user-images.githubusercontent.com/105681029/171945687-631a3931-ebb4-4fdd-83a9-24c15867efb8.png">

Proposed workaround is to ask users to supply a list of remote repositories at onboarding time, so these can be pre-populated in the project.

**Comment by mitovskaol** [comment]
@caggles Can you please provide an estimate for automating this function that now you have to do manually.
